import { Moment } from 'moment';
import { DayDto } from 'shared';

export enum CalendarActionTypes {
  CURRENT_DATE_CHANGED = 'CURRENT_DATE_CHANGED',

  FETCH_DAYS_STARTED = 'FETCH_DAYS_STARTED',
  FETCH_DAYS_SUCCESS = 'FETCH_DAYS_SUCCESS',
  FETCH_DAYS_ERROR = 'FETCH_DAYS_ERROR',

  FETCH_DAY_DETAILS_STARTED = 'FETCH_DAY_DETAILS_STARTED',
  FETCH_DAY_DETAILS_SUCCESS = 'FETCH_DAY_DETAILS_SUCCESS',
  FETCH_DAY_DETAILS_ERROR = 'FETCH_DAY_DETAILS_ERROR',

  DELETE_TASK_STARTED = 'DELETE_TASK_STARTED',
  DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR = 'DELETE_TASK_ERROR',
}

export type CalendarState = {
  currentDate: Moment;
  selectedDayDetails: DayDto;
  fetchedDays: DayDto[];
};
